### ISSUE TITLE
CI/CD: Optimize workflow triggers and caching strategy

### ISSUE THREAD

**Issue by mmiura-2351** [mmiura-2351/mc-server-dashboard-ui#5]
## Problem
The CI workflow configuration has overly broad triggers and potential optimization opportunities.

## Details
**File**: `.github/workflows/ci.yml:4-8`

### Current Issues:
1. **Broad branch triggers**: `branches: ["**"]` runs CI on every branch, including feature branches
2. **Resource usage**: May cause unnecessary CI runs for experimental or draft branches
3. **No caching strategy**: Missing dependency caching for faster builds
4. **No matrix builds**: Could benefit from testing multiple Node.js versions

### Current Configuration:
```yaml
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
```

## Solution
1. **Optimize triggers**: Only run on main branches and PRs to main
2. **Add dependency caching**: Cache `node_modules` for faster builds
3. **Add Node.js matrix**: Test on multiple Node.js versions
4. **Add build caching**: Cache build artifacts

## Suggested Configuration:
```yaml
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
```

## Priority
Low - Current setup works but could be more efficient
